#!/usr/bin/python

# Check out the README:
# https://github.com/edmund-huber/jsonq/blob/master/README.md

from optparse import OptionParser
import re
import sys

try:
    # simplejson is typically faster than standard-library json
    import simplejson as json
except ImportError:
    import json

class FilteredObject(object):
    """Represents an incrementally built query-filtered JSON object.

    >>> f = FilteredObject()
    >>> f.add_key('narf'); f.add_array(); f.add_key('zoop'); f.add_val(1);
    >>> f.get_result()
    {'narf': [{'zoop': 1}]}
    """

    def __init__(self):
        # this is the object we're building
        self.result = None

        # next place to assign is always self.tip[self.last_subscript]
        self.tip = None
        self.last_subscript = None

    def get_result(self):
        """Get the finished object."""
        return self.result

    def add_key(self, key):
        """Set the current object tip to be a dictionary key."""
        if self.result is None:
            self.result = self.tip = {}
            self.last_subscript = key
            return

        new_tip = {}
        self.tip[self.last_subscript] = new_tip
        self.tip = new_tip
        self.last_subscript = key

    def add_array(self):
        """Set the current object tip to be an array of length 1."""
        if self.result is None:
            self.result = self.tip = [None]
            self.last_subscript = 0
            return

        new_tip = [None]
        self.tip[self.last_subscript] = new_tip
        self.tip = new_tip
        self.last_subscript = 0

    def add_val(self, val):
        """Set the current object tip to be an arbitrary value."""
        if self.result is None:
            self.result = val
        else:
            self.tip[self.last_subscript] = val

def find(args):
    """Find candidate queries that would match elements in the data on stdin."""

    # build a query as we go down into the JSON, if we find something
    # that matches put said query into the return list.
    def find_matches(j, subs, query):
        def match(s):
            if subs in str(s):
                return [(query, j)]
            else:
                return []
        if type(j) == list:
            return reduce(lambda l, i_e: l + find_matches(i_e[1], subs, query + '[' + str(i_e[0]) + ']'), enumerate(j), [])
        elif type(j) == dict:
            return reduce(lambda l, k_v: l + match(k_v[0]) + find_matches(k_v[1], subs, query + '.' + k_v[0]), j.items(), [])
        else:
            return match(j)

    # report on which queries to use to find things.
    for line in sys.stdin:
        j = json.loads(line)
        print 'for the input:  %s' % json.dumps(j)
        for subs in args:
            for query, result in find_matches(j, subs, ''):
                print 'using query "%s", jsonq would find:  %s' % (query, result)

def parse_queries(query_strs):
    """Convert `query_str` (the command-line arguments) to parsed queries."""

    # parse the given queries. Each parsed query is a list of
    # tuples. The first element of each tuple, if not None, is a
    # dictionary key. The second element " " " ", is an array index.
    queries = []
    for query_s in query_strs:
        original_query_s = query_s
        query = []
        while True:
            # dictionary keys may contain anything except ., [, or ], so [^.\[\]]+
            # maybe allow these chars also when backslash-escaped? meh.
            # array indices are digits, i.e., \d+
            m = re.match(r'((?P<select>\.[^.\[\]]+)|(?P<index>\[\d+\]))', query_s)
            if m:
                query_s = query_s[len(m.group(0)):]
                if m.group('select'):
                    q = m.group('select')[1:]
                    i = None
                elif m.group('index'):
                    q = None
                    i = int(m.group('index')[1:-1])
                else:
                    assert False
                query.append((q, i))
            elif query_s == '':
                break
            else:
                raise ValueError("Could not parse the query", original_query_s)
        queries.append(query)
    return queries

def query(queries, filter_data=False, strify=False):
    """Run `queries` against the data on stdin."""

    for line in sys.stdin:
        json_obj = json.loads(line)

        for query in queries:
            tip = json_obj
            if filter_data: filtered_obj = FilteredObject()

            try:
                for s, i in query:
                    if s is not None and i is None:
                        # this query item is an dictionary key:
                        if filter_data: filtered_obj.add_key(s)
                        tip = tip[s]
                    elif s is None and i is not None:
                        # this query item is an array subscript
                        if filter_data: filtered_obj.add_array()
                        tip = tip[i]
                    else:
                        assert False
                if filter_data: filtered_obj.add_val(tip)
            except KeyError:
                print 'null',
            else:
                obj_to_print = filtered_obj.get_result() if filter_data else tip
                str_to_print = str(obj_to_print) if strify else json.dumps(obj_to_print)
                print str_to_print,
        print

def main():
    parser = OptionParser(usage="%prog [options] queries")
    parser.add_option('-f', '--find', dest='find', default=False, action='store_true',
            help="Emit all queries that would match any of the arguments.")
    parser.add_option('-i', '--filter', dest='filter', default=False, action='store_true',
            help="Show the original object filtered by the query, not just the result.")
    parser.add_option('-s', '--str', dest='str', default=False, action='store_true',
            help="Coerce output with str() instead of dumping JSON.")
    options, args = parser.parse_args()

    if options.find:
        return find(args)
    else:
        queries = parse_queries(args)
        return query(queries, filter_data=options.filter, strify=options.str)

if __name__ == '__main__':
    sys.exit(main())
